### PR TITLE
[do not review] CDX-766 Tests

### PR DESCRIPTION
**Pull request by ThibodeauJF**

### CODE REVIEW

**Comment by ThibodeauJF** [comment]
I can't seem to be able to convert it back into a draft! I just wanted my tests to run 😢

**Comment by louis-bompart** [comment]
> I can't seem to be able to convert it back into a draft! I just wanted my tests to run 😢

image
?

**Comment by ThibodeauJF** [comment]
@louis-bompart I thought I didn't have the rights for it, button is *not* very visible either

**Comment by louis-bompart** [comment]
> @louis-bompart I thought I didn't have the rights for it, button is *not* very visible either

Oh yeah, I always forgot where it is. Tis silly

**Pull request closed without merging**
