### PR TITLE
chore: lint E2E files

### PR DESCRIPTION
**Pull request by y-lakhdar**
## Proposed changes

I had lint errors on my PR CDX-87 and I did not want to include the file linting in the PR scope.

CDX-406

### CODE REVIEW

**Comment by louis-bompart** [comment]
Should have failed in the main branch or in the PR that activated the mandatory accessiblity level keywords rule.

You should first investigate why it doesn't fail in the branch before fixing the error that you encountered.

**Comment by y-lakhdar** [comment]
> Should have failed in the main branch or in the PR that activated the mandatory accessiblity level keywords rule.
> 
> You should first investigate why it doesn't fail in the branch before fixing the error that you encountered.

Yes, we can open a Jira to address the eslint issue. In the meantime, I don't think this PR will hurt

**Comment by louis-bompart** [comment]
> > Should have failed in the main branch or in the PR that activated the mandatory accessiblity level keywords rule.
> > You should first investigate why it doesn't fail in the branch before fixing the error that you encountered.
> 
> Yes, we can open a Jira to address the eslint issue. In the meantime, I don't think this PR will hurt

No, I think this should be part of this Jira and of this PR actually
To be precise, you found errors, that's great (kinda?). Now, replicate that in the CI (i.e. controlled environment) and then and only then, fix the errors. Because like this you have precise and defined acceptance criteria for the fix of the CI. It'll allow us to be more confident that we fixed the gap in our tests.

**Review by olamothe — APPROVED** [review]

**Comment by y-lakhdar** [comment]
Fixed the eslint issues.
1. The `.eslintignore` in the cli package was ignoring the entire lib directory ([commit](https://github.com/coveo/cli/pull/278/commits/37958dd0cb292a4b072a78f7b26d12eef347031a))
2. cli-e2e was missing eslint package and script ([commit](https://github.com/coveo/cli/pull/278/commits/86cfd66360981c9868da192b5e248d2ebaade12b))

**Pull request merged**
