### PR TITLE
fix(cli): add a `--not-git` flag on the command `ui:create:vue`

### PR DESCRIPTION
**Pull request by y-lakhdar**
This flag is needed to prevent the tests from crashing.

The idea is to have a hidden `--test` flag for each `ui:create:` command. That way, we can adjust the instruction if it is running in test mode.

In the case of Vue.js, the test mode will add the `--no-git` flag, which will prevent the initialization of a git repository during the project creation.

Otherwise, the Vue CLI will return the following error.
```
missing username and email in git config, or failed to sign a commit
```

If you run the E2E tests in your local machines while having uncommitted changes, the Vue Cli will prompt a warning and wait for the user input.
Adding the `--no-git` flag will prevent this scenario

### CODE REVIEW

**Comment by louis-bompart** [comment]
@y-lakhdar for funsies, can you try to init the git config of not groot in the dockerfile or the bash files?
I ain't fond of doing a 'test path' in our logic, especially for E2E

**Comment by olamothe** [comment]
How about we add a `-- passthrough` kind of command ? 

That we document/make official. And you can use it to just "pass through options to the vue cli" ?
And then in our tests we would do `--passthrough not-git` or something similar to this ?

There could be some use by end users to be able to pass options to the vue CLI underneath.

**Comment by y-lakhdar** [comment]
I like the passthrough approach!

**Comment by y-lakhdar** [comment]
I'll close this one for now and will update the Dockerfile as proposed by @louis-bompart .
If we really need a `passthrough` feature, I'll create a separate Jira.

**Pull request closed without merging**
