### PR TITLE
change to absolute path

### PR DESCRIPTION
**Pull request by y-lakhdar**
https://coveord.atlassian.net/browse/CDX-347

## Testing

- [ ] Unit Tests:

- [ ] Functionnal Tests:

- [ ] Manual Tests:

### CODE REVIEW

**Comment by louis-bompart** [comment]
Is it still needed after the changes I made yesterday?

**Comment by y-lakhdar** [comment]
> Is it still needed after the changes I made yesterday?

No, I still get the following error
image

Steps to reproduce:
1. Create a empty folder ... anywhere
2. `cd /path/to/new/folder`
2. `/path/to/cli/packages/cli/bin/run pull`
3. `/path/to/cli/packages/cli/bin/run org:config:preview`

**Comment by louis-bompart** [comment]
> > Is it still needed after the changes I made yesterday?
> 
> No, I still get the following error
> image
> 
> Steps to reproduce:
> 
> 1. Create a empty folder ... anywhere
> 2. `cd /path/to/new/folder`
> 3. `/path/to/cli/packages/cli/bin/run pull`
> 4. `/path/to/cli/packages/cli/bin/run org:config:preview`

👍 Fixed in #267 , it was the 'deleteOldPreviews' that was causing issue, because it tried to scan an unexisting directory if you had no preview before (which is why I was confused at first)

**Comment by y-lakhdar** [comment]
Do you still want this PR open, or I can close it?

**Pull request closed without merging**
