### PR TITLE
doc(cli): readme-review

### PR DESCRIPTION
**Pull request by jpmarceau**
Je trouvais que le readme principal manquait un peu de viande, alors j'en ai ajouté.

### CODE REVIEW

**Comment by olamothe** [comment]
This is auto generated. 
This means it's going to get overwritten all the time.

**Comment by jpmarceau** [comment]
> This is auto generated.
> This sadly means it's going to get overwritten all the time.

Ho noes, that's unfortunate.
I see where the docstrings for the `Commands` section are extracted, but I can't seem to find how the `Usage` section is generated. Do you know of any simple way I could tweak it? I think an introductory paragraph or two would really help, but it's not a huge deal either. I want to add basically the same info to the readme at the root of the repo anyways.

**Comment by louis-bompart** [comment]
> > This is auto generated.
> > This sadly means it's going to get overwritten all the time.
> 
> Ho noes, that's unfortunate.
> I see where the docstrings for the `Commands` section are extracted, but I can't seem to find how the `Usage` section is generated. Do you know of any simple way I could tweak it? I think an introductory paragraph or two would really help, but it's not a huge deal either. I want to add basically the same info to the readme at the root of the repo anyways.

We can investigate how to customize this message, but that'd prolly require some leg work.
In the meantime, I invite you to not alter this ReadMe.md and works on the 'root' one ;)

I logged a spike to check what's up CDX-254. However I don't think it'll be our priority soon 😅

**Review by louis-bompart — CHANGES_REQUESTED** [review]
As explained above, bring the changes to the root readme instead.
We will tackle this one later.

**Review by louis-bompart — APPROVED** [review]

**Pull request merged**
